### ISSUE TITLE
Advanced Sampling

### ISSUE THREAD

**Issue by bdice** [MolSSI/molssi_driver_interface#22]
Cool project! I saw this repository was linked in a recent paper (https://aip.scitation.org/doi/10.1063/1.5052551). The approach of message-passing seems general enough to be useful for tons of applications. I have also done some work with [SSAGES](https://github.com/MICCoM/SSAGES-public), which seems it may overlap with this in some feature sets, namely advanced sampling. Its approach is a little different, just wanted to share that in case you hadn't seen it. :)

**Comment by taylor-a-barnes** [comment]
I apologize for the slow response.  Thank you very much for your kind words.  Supporting a wide variety of calculation types is definitely one of our goals.

There are several impressive projects that facilitate different aspects of code interoperability, and SSAGES is a great example.  Ultimately, we want to provide a utility that many different groups, including the developers of SSAGES, will find helpful.  With that in mind, feel free to let us know if you have any thoughts about what would be most helpful for you and your research.
